name: Minikube CI Test

on:
  pull_request:
    branches:
      - main  # Run on PRs to the main branch

jobs:
  deploy-to-minikube:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full repo checkout

      # Step 2: Set up Minikube
      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      # Step 3: Verify Minikube status (no error)
      - name: Check Minikube status
        run: minikube status
